name: Convert Texts to Unicode Escapes

on:
  push:
    paths:
      - 'texts.py'

jobs:
  convert_unicode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Виберіть потрібну версію Python

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements.txt found."

      - name: Convert texts.py to Unicode
        run: |
          python convert_to_unicode.py

      - name: Commit and Push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add texts_unicode.py
          git commit -m "Convert texts.py to Unicode escapes" || echo "No changes to commit"
          git push
