# mkdocs.yml
site_name: MLBB-BOSS Documentation
site_description: Документація для Mobile Legends Tournament Bot
site_author: MLBB-BOSS
repo_url: https://github.com/MLBB-BOSS/Mobile-Legends-Starts

theme:
  name: material  # Сучасна тема Material
  language: uk   # Українська мова
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append(".")
          selection:
            docstring_style: google

nav:
  - Головна: index.md
  - Посібник користувача:
    - 'Початок роботи': 'guide/getting-started.md'
    - 'Команди бота': 'guide/commands.md'
    - 'Турніри': 'guide/tournaments.md'
  - API:
    - 'Handlers': 'api/handlers.md'
    - 'Utils': 'api/utils.md'
    - 'Database': 'api/database.md'
  - Розробка:
    - 'Внесення змін': 'development/contributing.md'
    - 'Архітектура': 'development/architecture.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - footnotes

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MLBB-BOSS
