# states.py
from aiogram.fsm.state import StatesGroup, State

class MenuStates(StatesGroup):
    MAIN_MENU = State()
    NAVIGATION_MENU = State()
    HEROES_MENU = State()
    HERO_CLASS_MENU = State()
    BUILDS_MENU = State()
    COUNTER_PICKS_MENU = State()
    GUIDES_MENU = State()
    VOTING_MENU = State()
    M6_MENU = State()
    GPT_MENU = State()
    META_MENU = State()
    TOURNAMENTS_MENU = State()
    PROFILE_MENU = State()
    STATISTICS_MENU = State()
    ACHIEVEMENTS_MENU = State()
    SETTINGS_MENU = State()
    FEEDBACK_MENU = State()
    HELP_MENU = State()
    SEARCH_HERO = State()
    SUGGEST_TOPIC = State()
    CHANGE_USERNAME = State()
    UPDATE_ID = State()
    RECEIVE_FEEDBACK = State()
    REPORT_BUG = State()
    CREATE_TOURNAMENT = State()
    VIEW_TOURNAMENTS = State()