name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout репозиторія
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Налаштування Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Встановлення залежностей
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Лінтинг з flake8
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 src/ --max-line-length=88

      # Запуск тестів
      - name: Run Tests
        run: |
          pytest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # Checkout репозиторія
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Налаштування Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Встановлення залежностей
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Деплоймент на Heroku
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "your-heroku-app-name"
          heroku_email: "your-email@example.com"
