# .github/workflows/create_structure.yml
name: Create Repository Structure

on:
  workflow_dispatch:
  push:
    paths:
      - 'scripts/setup/heroes_data.json'

permissions:
  contents: write  # Дозволяє workflow створювати та змінювати файли у репозиторії

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install PyGithub

      - name: Run Structure Setup Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python scripts/setup/setup_structure.py
