name: Deploy to Heroku

on:
  push:
    branches:
      - aiogram-3x  # Гілка, на яку реагує GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Завантаження репозиторію
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Встановлення Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Встановлення залежностей (необов'язково для деплою на Heroku, але може бути корисним для тестування)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Аутентифікація в Heroku
      - name: Login to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "$HEROKU_API_KEY" | heroku login --interactive

      # 5. Деплой на Heroku
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v4.1.6 # Актуальна версія дії для деплою на Heroku
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }} # Назва вашого додатку на Heroku
          heroku_email: ${{ secrets.HEROKU_EMAIL }}       # Ваш email, зареєстрований на Heroku
          usedocker: false
