name: Deploy to Heroku

on:
  push:
    branches: 
      - aiogram-3x
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: aiogram-3x

      # Install Heroku CLI using the official installation script
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
          # Verify installation
          which heroku
          heroku --version

      # Add Heroku Remote and Deploy
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        run: |
          # Configure Git with Heroku credentials
          cat > ~/.netrc << EOF
          machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
          chmod 600 ~/.netrc

          # Add Heroku remote and push
          heroku git:remote -a mlbb
          git push heroku aiogram-3x:main --force

      - name: Verify deployment
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku ps --app mlbb
          heroku logs --tail --app mlbb --num 50
