name: Deploy to Heroku

on:
  push:
    branches: 
      - aiogram-3x
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_APP_NAME: mlbb
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: aiogram-3x

      # Using AkhileshNS/heroku-deploy action which handles authentication better
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "mlbb"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          branch: "aiogram-3x"

      - name: Verify deployment
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku ps --app mlbb
          heroku logs --tail --app mlbb --num 50
