name: Deploy to Heroku

on:
  push:
    branches:
      - aiogram-3x
default  # Запускати лише для гілки main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Завантаження репозиторію
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Встановлення Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11  # Ваша версія Python

    # 3. Встановлення залежностей
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Вхід у Heroku
    - name: Login to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo "machine api.heroku.com" > ~/.netrc
        echo "  login ${{ secrets.HEROKU_EMAIL }}" >> ~/.netrc
        echo "  password ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc
        echo "machine git.heroku.com" >> ~/.netrc
        echo "  login ${{ secrets.HEROKU_EMAIL }}" >> ~/.netrc
        echo "  password ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc

    # 5. Розгортання на Heroku
    - name: Deploy to Heroku
      env:
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        git push heroku HEAD:main --force
