name: Deploy to Heroku

on:
  push:
    branches: 
      - aiogram-3x
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: aiogram-3x

      # Install Heroku CLI using the official method
      - name: Install Heroku CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y heroku
          heroku --version

      # Set up Heroku credentials
      - name: Set up Heroku credentials
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        run: |
          cat > ~/.netrc << EOF
          machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
          chmod 600 ~/.netrc

      # Deploy directly using Git
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku https://git.heroku.com/mlbb.git
          git push heroku aiogram-3x:main --force

      # Verify deployment
      - name: Verify deployment
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku ps --app mlbb
          heroku logs --tail --app mlbb --num 50
