name: Deploy to Heroku

on:
  push:
    branches: 
      - aiogram-3x
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_APP_NAME: mlbb
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: aiogram-3x

      - name: Login to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "$HEROKU_API_KEY" | heroku auth:token

      # Using Heroku Deploy Action instead of manual git push
      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          branch: "aiogram-3x"
          
      - name: Verify deployment
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku ps --app $HEROKU_APP_NAME
          heroku logs --tail --app $HEROKU_APP_NAME --num 50
